name: Nuclei DAST Scan

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
      - 'feature/**'

jobs:
  nuclei-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Nuclei
        run: |
          curl -s https://api.github.com/repos/projectdiscovery/nuclei/releases/latest \
          | grep "browser_download_url.*linux_amd64.zip" \
          | cut -d '"' -f 4 \
          | wget -i - -O nuclei.zip
          unzip nuclei.zip
          chmod +x nuclei
          sudo mv nuclei /usr/local/bin/

      - name: Run CVE-specific Nuclei Scan
        run: |
          echo "Running CVE-specific Nuclei scan on https://todo-app-tj1h.onrender.com "
          nuclei -u https://todo-app-tj1h.onrender.com -t http/ -severity low,medium,high,critical -v -o nuclei-cve-results.txt

      - name: Display CVE Scan Results
        run: |
          echo "------ CVE Scan Results ------"
          cat nuclei-cve-results.txt
