name: SonarQube Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  sonarqube:
    name: SonarQube Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adoptopenjdk'

      - name: Cache SonarQube dependencies
        uses: actions/cache@v2
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar-${{ hashFiles('**/sonar-project.properties') }}
          restore-keys: |
            ${{ runner.os }}-sonar-

      - name: Run SonarQube analysis
        uses: sonarsource/sonarcloud-github-action@v1
        with:
          organization: 'your-sonarcloud-organization'  # Replace with your SonarCloud organization name (if using SonarCloud)
          token: ${{ secrets.SONARQUBE_TOKEN }}  # Uses the SonarQube token secret stored in GitHub Secrets

      - name: Quality Gate Check
        run: |
          curl -u ${{ secrets.SONARQUBE_TOKEN }} -X POST "https://sonarcloud.io/api/qualitygates/project_status?projectKey=your_project_key" \
          | jq -r '.projectStatus.status'  # Replace 'your_project_key' with your actual SonarQube project key
          if [ "$status" != "OK" ]; then
            echo "SonarQube quality gate failed"
            exit 1
          fi
