name: TruffleHog Secret Scan

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
      - 'feature/**'

jobs:
  trufflehog:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run TruffleHog
        uses: trufflesecurity/trufflehog@main
        with:
          path: './app'           # scan only your application code
          extra_args: >          # pass any TruffleHog CLI flags here
            --only-verified       # your desired flag
            --max_depth 5         # limit history depth
            --regex               # use regex scanning
            --entropy=False       # disable entropy for fewer false positives
