name: TruffleHog Negative Test

on:
  push:
    branches:
      - feature/trufflehog-negative-case  # Ensure you have the correct branch

jobs:
  trufflehog-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Fetch all branches and commits
        run: git fetch --all

      - name: Install TruffleHog
        run: |
          curl -sSL https://github.com/trufflesecurity/trufflehog/releases/download/v3.88.29/trufflehog-linux-amd64-3.88.29.tar.gz | tar xz
          mv trufflehog-linux-amd64-3.88.29/trufflehog /usr/local/bin/trufflehog

      - name: Run TruffleHog scan
        run: trufflehog --json --no-progress --since commit <target-repository-url>
