name: TruffleHog Secret Scan

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
      - 'feature/**'

jobs:
  trufflehog:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run TruffleHog
        uses: trufflesecurity/trufflehog@main
        with:
          path: './app'
          extra_args: |
            --only-verified
